### ISSUE TITLE
[feat/auth] found issues

### ISSUE THREAD

**Issue by Laejun-Kim** [hyewon-han/baple#22]
- [x] 회원가입할때 회원가입 버튼을 눌러서 성공적이게 가입해도 아무런 피드백이 없음 뭐 알림이 뜬다거나 로그인 시킨다거나, 홈으로 리디렉션 한다던가 하는 조치가 필요
 - [x] 회원가입시 비밀번호 입력할때 '조건에 맞게 입력' 하라는게 애매함. 조건이 뭔지 알려주든가 해야함. 사용자가 비밀번호 규칙을 기억하고 있을 것이라고 기대하기 어려움
![image](https://github.com/hyewon-han/baple/assets/49670820/16d25174-d25f-4eac-bc5a-cb249a14c37f)
 

 - [x]  마이페이지에서 로그아웃 후에도 마이페이지에 남아있음. 심지어 뒤로가기나 앞으로가기로 마이 페이지에 재진입이 가능한데 이때도 로그인 되어 있는 것으로 표시됨.
 
 - [x]  로그아웃 하였을때도 isLoggedIn redux state가 true 로 유지됨
 ![image](https://github.com/hyewon-han/baple/assets/49670820/590289ad-15a1-4f25-9f32-31c16d699eca)

**Comment by hyewon-han** [comment]
회원 가입 시 이미 존재하는 유저인 경우 "이미 존재하는 아이디 입니다" 라는 알림을 주었습니다.
성공적으로 회원가입시 홈으로 이동하도록 수정했습니다.

"비밀번호를 조건에 맞게 입력하세요" 부분을 '비밀번호는 영문, 숫자 포함 8자 이상 입니다.' 의 문자열로 수정했습니다.

로그아웃 이벤트 발생 시 홈으로 이동하도록 수정했습니다. 로그아웃 시 redux store 의 isLoggedIn state를 false 로 수정하였습니다.

**Comment by Laejun-Kim** [comment]
확인했습니다 :)
