### ISSUE TITLE
[fix/review] 디버깅 + 리팩토링 + 스타일링

### ISSUE THREAD

**Issue by Laejun-Kim** [hyewon-han/baple#95]
#### 오작동 fix
 - [x] 삭제 실시간 반영
 - [x] 좋아요 수 실시간 반영
 - [x] 댓글 수 실시간 반영
#### CSS
 - [x] 반응형 스타일링 
 - [x] 웹 버전 스타일링
#### 리팩토링
 - [x] placeCard 용 rpc 함수 만들어보기
 - [x] 훅 뺄 수 있는건 커스텀 훅으로 빼기
 - [x] 메인 페이지에서 ssr 구현 시도

**Comment by hyewon-han** [comment]
마이페이지에 내가쓴 리뷰 삭제 실시간 반영은 제가 했습니다~!
